Random {data-navmenu="Parameters"}
================================================================================

Row {.tabset}
--------------------------------------------------------------------------------

### Recruitment

```{r}
plot_report(random_par$log_r, color = ~model, legendgroup = ~model, colors = cols, ylab = "Recruitment (r)")
```

`r if ("log_n" %in% names(random_par)) "### Abundance (N)"`

```{r, eval = "log_n" %in% names(random_par)}
plot_report(random_par$log_n, color = ~model, legendgroup = ~model, colors = cols, frame = ~age, ylab = "Latent abundance (n)")
```

`r if ("log_n0" %in% names(random_par)) "### Initial abundance"`

```{r, eval = "log_n0" %in% names(random_par)}
plot_report(random_par$log_n0, x = ~age, xlab = "Age", color = ~model, legendgroup = ~model, colors = cols, ylab = "Initial abundance")
```

### Fishing mortality (F)

```{r}
plot_report(random_par$log_f, x = ~year, color = ~model, legendgroup = ~model, colors = cols, frame = ~age, ylab = "Latent F (f)")
```

`r if ("log_m" %in% names(random_par)) "### Natural mortality (M)"`

```{r, eval = "log_m" %in% names(random_par)}
plot_report(random_par$log_m, x = ~year, color = ~model, legendgroup = ~model, colors = cols, frame = ~age_block, ylab = "Latent M (m)")
```

```{r, results = "asis"}
for (term in names(formula_effects$levels)) {
  effect <- formula_effects$levels[[term]]
  rendered <- knitr::knit_child("one_formula_effect.Rmd", quiet = TRUE)
  cat(rendered, sep = "\n")
}
```
