
Inputs {data-navmenu="Tables"}
================================================================================

Row {.tabset}
--------------------------------------------------------------------------------

```{r}
obs_list <- lapply(names(fits), function(nm) fits[[nm]]$dat$obs)
names(obs_list) <- names(fits)
obs_stack <- stack_nested(obs_list, label = "model", label_type = "factor")
```


### Catch-at-age

```{r}
table_link(obs_stack$catch, table_name = "catch")
knitr::kable(obs_stack$catch)
```

### Index-at-age

```{r}
table_link(obs_stack$index, table_name = "index")
knitr::kable(obs_stack$index, digits = 2)
```

### Weight-at-age

```{r}
table_link(obs_stack$weight, table_name = "weight")
knitr::kable(obs_stack$weight, digits = 2)
```

### Maturity-at-age

```{r}
table_link(obs_stack$maturity, table_name = "maturity")
knitr::kable(obs_stack$maturity, digits = 2)
```


Settings {data-navmenu="Tables"}
================================================================================

Row {.tabset}
--------------------------------------------------------------------------------

### SSB timing

```{r, results = "asis"}
knitr::kable(ssb_timing, format = "html")
```

### Function calls

```{r, results = "asis"}
call_fits <- Filter(function(fit) inherits(fit, "tam_fit"), fits)
calls <- lapply(call_fits, `[[`, "call")
if (length(calls)) {
  calls_parsed <- sapply(calls, deparse1, width.cutoff = 50L, collapse = "\n")
  calls_html <- paste("<pre style='margin:0; white-space:pre-wrap'>\n",
                      calls_parsed,
                      "\n</pre>")
  calls_df <- data.frame(Model = names(calls), Call = calls_html)
  cat('<div style="height: 100%; overflow-y: auto;">\n\n')
  print(knitr::kable(calls_df, format = "html", escape = FALSE, col.names = NULL))
  cat('\n</div>\n\n')
}
```


Output {data-navmenu="Tables"}
================================================================================

Row {.tabset}
--------------------------------------------------------------------------------

### Fixed parameters

```{r}

table_link(fixed_par, table_name = "fixed_par")
knitr::kable(fixed_par, digits = 3)

```

### Random parameters

```{r, results = "asis", echo = FALSE}

for (nm in names(random_par)) {
  tbl <- random_par[[nm]]
  cat("#### ", nm, "\n\n", sep = "")
  print(knitr::kable(tbl, digits = 3))
  cat("\n\n")
}

```

### Abundance

```{r, eval = !is.null(pop$abundance)}
table_link(pop$abundance, table_name = "abundance")
d <- pop$abundance
d$year <- as.character(d$year)
d$se <- format(d$se, digits = 1)
knitr::kable(d, digits = 0, format.args = list(big.mark = ","))
```

### Recruitment

```{r, eval = !is.null(pop$recruitment)}
table_link(pop$recruitment, table_name = "recruitment")
d <- pop$recruitment
d$year <- as.character(d$year)
d$se <- format(d$se, digits = 1)
knitr::kable(d, digits = 0, format.args = list(big.mark = ","))
```

### Spawning stock biomass

```{r, eval = !is.null(pop$ssb)}
table_link(pop$ssb, table_name = "ssb")
d <- pop$ssb
d$year <- as.character(d$year)
d$se <- format(d$se, digits = 1)
knitr::kable(d, digits = 0, format.args = list(big.mark = ","))
```

### Average F

```{r, eval = !is.null(pop$F_bar)}
table_link(pop$F_bar, table_name = "F_bar")
d <- pop$F_bar
d$year <- as.character(d$year)
knitr::kable(d, digits = 3)
```

### Average M

```{r, eval = !is.null(pop$M_bar)}
table_link(pop$M_bar, table_name = "M_bar")
d <- pop$M_bar
d$year <- as.character(d$year)
knitr::kable(d, digits = 3)
```

### Metrics-at-age

```{r}
keys <- c("age", "year", "model", "is_proj")
metric_tables <- Filter(Negate(is.null), lapply(c("N", "F", "M"), function(metric) {
  d <- pop[[metric]]
  if (is.null(d) || !nrow(d)) return(NULL)
  fields <- setdiff(names(d), keys)
  names(d)[match(fields, names(d))] <- ifelse(fields == "est", metric, paste0(fields, "_", metric))
  d
}))
d <- Reduce(function(x, y) merge(x, y, by = keys), metric_tables)
table_link(d, table_name = "Metrics-at-age")
knitr::kable(d, digits = 3)
```



